eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      global-cors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            exposedHeaders: "*"
#      routes:
#        - id: user-service
#          uri: http://localhost:8090
#          predicates:
#            - Path=/api/v1/**
#          filters:
#            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
#        - id: product-web-app
#          uri: http://localhost:4000
#          predicates:
#            - Path=/api/v1/**
#          filters:
#            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
#        - id: transaction-service
#          uri: http://localhost:8060
#          predicates:
#            - Path=/api/v1/**
#          filters:
#            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
#        - id: bank-service
#          uri: http://localhost:8070
#          predicates:
#            - Path=/api/v1/**
#          filters:
#            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
#server:
#  port: 8080
#spring:
#  main:
#     web-application-type: reactive
#  application:
#    name: "API-GATEWAY"
#  cloud:
#    compatibility-verifier:
#      enabled: false
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      global-cors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            exposedHeaders: "*"
#      routes:
#        - id: bank-service
#          uri: http://localhost:8070
#          predicates:
#            - Path=/api/v1/**
#          filters:
#            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
#        - id: user-service
#          uri: http://localhost:8090
#          predicates:
#            - Path=/api/v1/**
#          filters:
#            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
#        - id: product-web-app
#          uri: http://localhost:4000
#          predicates:
#            - Path=/api/v1/**
#          filters:
#            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
#        - id: transaction-service
#          uri: http://localhost:8060
#          predicates:
#            - Path=/api/v1/**
#          filters:
#            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}